<script type="text/javascript" src="/js/donate.js"></script>
<link rel="stylesheet" type="text/css" href="/css/donate.css">
<!-- content -->
<div id="content" class="site-wrap">
	<div class="donate_head">
		<a class="to_donate" href="#" target="_self">我要捐赠</a>
		<a class="go_donate_index" href="#" target="_self">捐赠首页</a>
		<!-- <a class="go_index" href="/" target="_self">易书首页</a> -->
	</div>
	<div class="don_wrap">
		<div class="don_list inner_01">
			<ul>
				<li class="list_li">
					<img class="icon_list01" src="/images/donate_list.png">
					<img class="icon_list02" src="/images/donate_list2.png">
					<div class="left">
						<div class="point_warp ava_warp">
							<img class="round_01" src="/images/donate_ava.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="donor_info donate_bor">
							<div class="tit donate_bor_top">捐赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="donor_name">
									<b>姓名：</b>
									<span>王小1</span>
								</p>
								<p class="book_name">
									<b>书名：</b>
									<span>《钢铁是怎样炼成的》</span>
								</p>
								<p class="col_name">
									<b>专业：</b>
									<span>机械制造及其自动化</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
					<div class="mid donor_info">
						<div class="mid_up mid_cont">
							<div class="book_cover inner_left">
								<div class="donate_bor_left tit">
									书籍封面
								</div>
								<div class="cover_wrap left_wrap">
									<div class="inner">
										<img onload="$(this).resizeImage2(true, 112,120)" src="/images/book-cover-mid04.png">
									</div>
								</div>
							</div>
							<div class="don_msg inner_right">
								<div class="don_msg_wrap right_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本
									</div>
								</div>
								<div class="donate_bor_rig tit">
									捐赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="mid_down mid_cont">
							<div class="qinZhiLian_msg inner_left">
								<div class="donate_bor_left tit">
									青志联寄语
								</div>
								<div class=" left_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本 2
									</div>
								</div>
							</div>
							<div class="given_msg inner_right">
								<div class=" right_wrap">
									<div class="com_msg inner">
										谢谢姐姐，我会好好努力，成为像姐姐一样对国家有用的人才！
									</div>
								</div>
								<div class="donate_bor_rig tit">
									获赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="right">
						<div class="point_warp gain_wrap">
							<img class="round_01" src="/images/donate_shouqu.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="rece_info donate_bor">
							<div class="tit donate_bor_top">受赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="rece_name">
									<b>姓名：</b>
									<span>王小二</span>
								</p>
								<p class="sex">
									<b>性别：</b>
									<span>男</span>
								</p>
								<p class="birth">
									<b>生日：</b>
									<span>2000/02/03</span>
								</p>
								<p class="address">
									<b>地址：</b>
									<span>合肥饱和小学三（1）班</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</li>
				<li class="list_li">
					<img class="icon_list01" src="/images/donate_list.png">
					<img class="icon_list02" src="/images/donate_list2.png">
					<div class="left">
						<div class="point_warp ava_warp">
							<img class="round_01" src="/images/donate_ava.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="donor_info donate_bor">
							<div class="tit donate_bor_top">捐赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="donor_name">
									<b>姓名：</b>
									<span>王小2</span>
								</p>
								<p class="book_name">
									<b>书名：</b>
									<span>《钢铁是怎样炼成的》</span>
								</p>
								<p class="col_name">
									<b>专业：</b>
									<span>机械制造及其自动化</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
					<div class="mid donor_info">
						<div class="mid_up mid_cont">
							<div class="book_cover inner_left">
								<div class="donate_bor_left tit">
									书籍封面
								</div>
								<div class="cover_wrap left_wrap">
									<div class="inner">
										<img onload="$(this).resizeImage2(true, 112,120)" src="/images/book-cover-mid04.png">
									</div>
								</div>
							</div>
							<div class="don_msg inner_right">
								<div class="don_msg_wrap right_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本
									</div>
								</div>
								<div class="donate_bor_rig tit">
									捐赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="mid_down mid_cont">
							<div class="qinZhiLian_msg inner_left">
								<div class="donate_bor_left tit">
									青志联寄语
								</div>
								<div class=" left_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本 2
									</div>
								</div>
							</div>
							<div class="given_msg inner_right">
								<div class=" right_wrap">
									<div class="com_msg inner">
										谢谢姐姐，我会好好努力，成为像姐姐一样对国家有用的人才！
									</div>
								</div>
								<div class="donate_bor_rig tit">
									获赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="right">
						<div class="point_warp gain_wrap">
							<img class="round_01" src="/images/donate_shouqu.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="rece_info donate_bor">
							<div class="tit donate_bor_top">受赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="rece_name">
									<b>姓名：</b>
									<span>王小二</span>
								</p>
								<p class="sex">
									<b>性别：</b>
									<span>男</span>
								</p>
								<p class="birth">
									<b>生日：</b>
									<span>2000/02/03</span>
								</p>
								<p class="address">
									<b>地址：</b>
									<span>合肥饱和小学三（1）班</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</li>
				<li class="list_li">
					<img class="icon_list01" src="/images/donate_list.png">
					<img class="icon_list02" src="/images/donate_list2.png">
					<div class="left">
						<div class="point_warp ava_warp">
							<img class="round_01" src="/images/donate_ava.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="donor_info donate_bor">
							<div class="tit donate_bor_top">捐赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="donor_name">
									<b>姓名：</b>
									<span>王小3</span>
								</p>
								<p class="book_name">
									<b>书名：</b>
									<span>《钢铁是怎样炼成的》</span>
								</p>
								<p class="col_name">
									<b>专业：</b>
									<span>机械制造及其自动化</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
					<div class="mid donor_info">
						<div class="mid_up mid_cont">
							<div class="book_cover inner_left">
								<div class="donate_bor_left tit">
									书籍封面
								</div>
								<div class="cover_wrap left_wrap">
									<div class="inner">
										<img onload="$(this).resizeImage2(true, 112,120)" src="/images/book-cover-mid04.png">
									</div>
								</div>
							</div>
							<div class="don_msg inner_right">
								<div class="don_msg_wrap right_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本
									</div>
								</div>
								<div class="donate_bor_rig tit">
									捐赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="mid_down mid_cont">
							<div class="qinZhiLian_msg inner_left">
								<div class="donate_bor_left tit">
									青志联寄语
								</div>
								<div class=" left_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本 2
									</div>
								</div>
							</div>
							<div class="given_msg inner_right">
								<div class=" right_wrap">
									<div class="com_msg inner">
										谢谢姐姐，我会好好努力，成为像姐姐一样对国家有用的人才！
									</div>
								</div>
								<div class="donate_bor_rig tit">
									获赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="right">
						<div class="point_warp gain_wrap">
							<img class="round_01" src="/images/donate_shouqu.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="rece_info donate_bor">
							<div class="tit donate_bor_top">受赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="rece_name">
									<b>姓名：</b>
									<span>王小4</span>
								</p>
								<p class="sex">
									<b>性别：</b>
									<span>男</span>
								</p>
								<p class="birth">
									<b>生日：</b>
									<span>2000/02/03</span>
								</p>
								<p class="address">
									<b>地址：</b>
									<span>合肥饱和小学三（1）班</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</li>
				<li class="list_li">
					<img class="icon_list01" src="/images/donate_list.png">
					<img class="icon_list02" src="/images/donate_list2.png">
					<div class="left">
						<div class="point_warp ava_warp">
							<img class="round_01" src="/images/donate_ava.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="donor_info donate_bor">
							<div class="tit donate_bor_top">捐赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="donor_name">
									<b>姓名：</b>
									<span>王小4</span>
								</p>
								<p class="book_name">
									<b>书名：</b>
									<span>《钢铁是怎样炼成的》</span>
								</p>
								<p class="col_name">
									<b>专业：</b>
									<span>机械制造及其自动化</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
					<div class="mid donor_info">
						<div class="mid_up mid_cont">
							<div class="book_cover inner_left">
								<div class="donate_bor_left tit">
									书籍封面
								</div>
								<div class="cover_wrap left_wrap">
									<div class="inner">
										<img onload="$(this).resizeImage2(true, 112,120)" src="/images/book-cover-mid04.png">
									</div>
								</div>
							</div>
							<div class="don_msg inner_right">
								<div class="don_msg_wrap right_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本
									</div>
								</div>
								<div class="donate_bor_rig tit">
									捐赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="mid_down mid_cont">
							<div class="qinZhiLian_msg inner_left">
								<div class="donate_bor_left tit">
									青志联寄语
								</div>
								<div class=" left_wrap">
									<div class="inner com_msg">
										希望这本书能够陪伴你成长，长成像保尔·柯察金一样坚强勇敢的人，加油！ 副本 2
									</div>
								</div>
							</div>
							<div class="given_msg inner_right">
								<div class=" right_wrap">
									<div class="com_msg inner">
										谢谢姐姐，我会好好努力，成为像姐姐一样对国家有用的人才！
									</div>
								</div>
								<div class="donate_bor_rig tit">
									获赠寄语
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="right">
						<div class="point_warp gain_wrap">
							<img class="round_01" src="/images/donate_shouqu.png">
							<img class="line_01" src="/images/donate_lin3.png">
							<img class="line_02" src="/images/donate_lin3.png">
						</div>
						<div class="rece_info donate_bor">
							<div class="tit donate_bor_top">受赠者信息</div>
							<div class="detail donate_bor_bot">
								<p class="rece_name">
									<b>姓名：</b>
									<span>王小二</span>
								</p>
								<p class="sex">
									<b>性别：</b>
									<span>男</span>
								</p>
								<p class="birth">
									<b>生日：</b>
									<span>2000/02/03</span>
								</p>
								<p class="address">
									<b>地址：</b>
									<span>合肥饱和小学三（1）班</span>
								</p>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</li>
			</ul>
			<div class="btn_func">
				<a class="prev" href="javascript:">前一个</a>
				<a class="next" href="javascript:">后一个</a>
			</div>
		</div>
		<div class="don_rule">
			<p><b>捐赠规则: </b>啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊</p>
		</div>
	</div>
	<div class="bd">
	</div>
	<div class="select-wrap">
		<h2 class="title-h1">
			<span class="title-h1-text">本组捐赠信息已浏览完毕</span>
			<b class="close" title="关闭">×</b>
		</h2>
		<div class="select_btn">
			<a href="javascript:" class="change_group" data-group="1">跳转到下一组</a>
			<a href="javascript:" class="look_again">重新浏览</a>
		</div>
		<div class="clear"></div>
	</div>
