
	<!-- 他的求书 -->
	<h2  class="GM-h2"><img src="/images/guestmode-h201.png"></h2>
	<div class='table_border GM-table-boeder'></div>
	<table class="table_list GM-table">
		<thead>
			<tr>
				<th>书名</th>
				<th>喊话内容</th>
				<th>求书时间</th>
				<th>交易状态</th>
			</tr>
		</thead>
		<tbody class='table_list_tbody'  style='display:table-row-group'>
		<!-- 输出求书信息 start -->
		<?php foreach ($this->buyBook as $buyValue) { ?>
			<tr>
				<td class="bookname-td"><?php echo $buyValue['buy_bookname']; ?></td>
				<td  class="content-td" style="width:250px;"><?php echo $buyValue['buy_content']; ?></td>
				<td><?php echo $buyValue['time']; ?></td>
				<td class='dealing_state_going'>求书中</td>
			</tr>
		<?php } ?>
		<!-- 输出求书信息 end -->
		</tbody>
	</table>
	<div class="clear"></div>
	<div class="turn-page-wrap">
		<ul class="turn_page_ul">
			<li class="first-page"><a style="<?php echo $this->pageNav['firstStyle']; ?>" href="<?php echo $this->pageNav['firstUrl']; ?>">首页</a></li>
			<li class="pre-page"><a style="<?php echo $this->pageNav['preStyle']; ?>" href="<?php echo $this->pageNav['preUrl']; ?>">上一页</a></li>
			<li style="color:#690;"><span class="cur-page"><?php echo $this->page; ?></span>/<span class="total-page"><?php echo $this->pages; ?></span></li>
			<li class="next-page"><a style="<?php echo $this->pageNav['nextStyle']; ?>" href="<?php echo $this->pageNav['nextUrl']; ?>">下一页</a></li>
			<li class="last-page"><a style="<?php echo $this->pageNav['lastStyle']; ?>" href="<?php echo $this->pageNav['lastUrl']; ?>">尾页</a></li>
		</ul>
	</div>