
<style type="text/css">
	/*将footer钉在底部*/
	body,html{
		height: 100%;
	}
	.wrap{
		position: relative;
		min-height: 100%;
	}
	#footer-wrap{
		position: absolute;
		bottom: 0px;
		left: 0px;
		width: 100%;
	}
	#content{
		margin-top: 50px;
	}
	#content p{
		font-family: '微软雅黑';
		font-size: 20px;
		color: #1d1b1a;
	}
</style>
<!-- content -->
<div id="content" class="site-wrap">
	<p><img src="/images/buliding.gif"></p>
	<p>程序猿正在疯狂加班中...</p>
</div>