
<link rel="stylesheet" type="text/css" href="/css/introduce.css">
<!-- content -->
<div id="content" class="site-wrap" style="min-height:214px">
	<h2 class="title-h1">
		<span class="title-h1-text">制作团队</span>
		<div class="clear"></div>
	</h2>
	<table id="list">
		<tbody>
			<tr>
				<th>项目总负责人</th>
				<td>@<a href="http://weibo.com/u/3167587853" target="_blank">蔡小萍</a></td>
				<th>技术后台</th>
				<td>@<a href="http://weibo.com/5stranger" target="_blank">陈健培</a></td>
			</tr>
			<tr>
				<th>项目推广</th>
				<td>@<a href="http://weibo.com/gouphigh" target="_blank">俞梦君</a></td>
				<th>技术前台</th>
				<td>@<a href="http://weibo.com/u/2680653253" target="_blank">刘廷建</a></td>
			</tr>
			<tr>
				<th rowspan="2">美工</th>
				<td>@<a href="http://weibo.com/u/1924472943" target="_blank">郑长玲</a></td>
				<th rowspan="2">用户体验</th>
				<td>@<a href="http://weibo.com/u/2384973171" target="_blank">邬胜芳</a></td>
			</tr>
			<tr>
				<td>@<a href="http://weibo.com/u/3218721402" target="_blank">丁晶晶</a></td>
				<td>@<a href="http://t.qq.com/niyinlong475581218" target="_blank">罗亮</a></td>
			</tr>
		</tbody>
	</table>
</div>
