
		<style type="text/css">
			/*将footer钉在底部*/
			body,html{
				height: 100%;
			}
			.wrap{
				position: relative;
				min-height: 100%;
			}
			#footer-wrap{
				left:0px;
				position: absolute;
				bottom: 0px;
				width: 100%;
			}
			#content{
				margin-top: 50px;
			}
			#content p{
				font-family: '微软雅黑';
				font-size: 24px;
				color: #1d1b1a;
			}
			#content p a{
				color: #ec7150;
			}
			#content .tiaozhuan{
				font-size: 14px;
				font-weight: normal;
				margin-top: 20px;
			}
		</style>
		<!-- content -->
		<div id="content" class="site-wrap">
			<p>你已发布成功！</p>
			<p>去<a href="<?php echo $this->nextUrl; ?>"><?php echo $this->nextPosition; ?></a>看看 or <a href="<?php echo $this->continue; ?>">继续<?php echo $this->nextDo; ?></a></p>    
			<!-- toHref 属性即为所要跳转的页面地址，注意不能省去http://,否则报错 -->
			<p class="tiaozhuan"><span id="totalSecond" toHref="<?php echo $this->nextUrl; ?>">5</span>秒之后自动跳转到<a href="<?php echo $this->nextUrl; ?>"><?php echo $this->nextPosition; ?></a></p>
		</div>
		<script language="javascript" type="text/javascript">
			var totalSecond = document.getElementById('totalSecond');
			var second = totalSecond.textContent;
			if (navigator.appName.indexOf("Explorer") > -1) {
				second = totalSecond.innerText;
			} else {
				second = totalSecond.textContent;
			}
			setInterval(redirect, 1000);
			function redirect() {
				if (second < 0) {
					location.href = totalSecond.getAttribute('toHref'); // 地址
				} else {
					if (navigator.appName.indexOf("Explorer") > -1) {
						totalSecond.innerText = second--;
					} else {
						totalSecond.textContent = second--;
					}
				}
			}
</script>