
		<link rel="stylesheet" type="text/css" href="/css/showbook.css">
		<script type="text/javascript" src="/js/plugin-side.js"></script>
		<script type="text/javascript">
		$(function(){
			$('.book-cover img').resizeImage(true, 285,386); 
				$('.spotlight-list img').resizeImage(true,111,145); 
				$('.history-list img').resizeImage(true,92,120); 
		})
		</script> 
		<!-- content -->
		<div id="content" class="site-wrap">
			<div class="left">
				<div class="book-info-wrap">
					<h2 class="title-h1">
						<span class="title-h1-text">书籍详情</span>
						<div class="clear"></div>
					</h2>
					<div class="book-info-inner">
						<h3><?php echo $this->bookInfo['book']['book_name']; ?></h3>
						<div class="book-cover-wrap">
							<div class="book-cover">
								<a href="javascript:void(0)">
									<img src="<?php echo $this->bookInfo['book']['photo_path']; ?>">
								</a>
							</div>
						</div>
						<div class="book-info-dl">
							<dl>
								<dt>书名:</dt>
								<dd><?php echo $this->bookInfo['book']['book_name']; ?></dd>
								<dt>出版社:</dt>
								<dd><?php echo $this->bookInfo['book']['publish']; ?></dd>
								<dt>适用专业:</dt>
								<dd><?php echo $this->bookInfo['book']['college']; ?></dd>
								<dt class='original-price-dt'>原价:</dt>
								<dd class='original-price-dd'><?php echo $this->bookInfo['book']['former_price']; ?></dd>
								<dt class='going-price-dt'>现价:</dt>
								<dd class='going-price-dd'><?php echo $this->bookInfo['book']['now_price']; ?></dd>
								<div class="clear"></div>
								<dt>书籍描述:</dt>
								<dd style="word-wrap:break-word;overflow:hidden;"><?php echo $this->bookInfo['book']['infor']; ?></dd>
								<dt>发布人:</dt>
								<dd><a href="/person/index/person/<?php echo $this->bookInfo['user']['user_id']; ?>" target="_blank"><?php echo $this->bookInfo['user']['user_name']; ?></a></dd>
								<dt>发布时间:</dt
								>
								<dd><?php echo $this->bookInfo['sale']['start_time']; ?></dd>
								<dt>过期时间:</dt>
								<dd><?php echo $this->bookInfo['sale']['end_time']; ?></dd>
								<dt>联系电话:</dt>
								<?php if ($this->userOnload) { ?>
								<dd style='font-size:20px;'><?php echo $this->bookInfo['user']['tel']; ?></dd>
								<?php } else { ?>
								<dd style='font-size:20px;'><img src="/images/phone-icon.png"><a href="<?php echo $this->loginUrl; ?>" class="get-tel">登录查看</a></dd>
								<?php } ?>
							</dl>
						</div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="clear"></div>
				<div class="recommend-wrap">
					<h2 class="title-h1">
						<span class="title-h1-text">猜你喜欢</span>
						<div class="clear"></div>
					</h2>
					<div class="spotlight-wrap">
						<div class="slide-nav">
							<div class="arrow-left prev" title="上一本">
							</div>
							<div class="arrow-right next" title="下一本">
							</div>
						</div>
						<div class="spotlight-list">
							<ul class="spotlight-list-ul">
							<!-- 输出推荐书籍 start -->
							<?php foreach ($this->recommend as $value) { ?>
								<li>
									<a href="<?php echo $value['bookUrl']; ?>" title='点击查看详细信息'>
										<img src="<?php echo $value['photo_path']; ?>">
									</a>	
									<p><a href="<?php echo $value['bookUrl']; ?>" title='点击查看详细信息'><?php echo $value['book_name']; ?></a></p>
								</li>
							<?php } ?>
							<!-- 输出推荐书籍 end -->
							</ul>

						</div>
					</div>
				</div>
			</div>
			<div class="right">
				<h3 class="main-bgCol-fontFam"><?php echo $this->sideTitle; ?></h3>
				<div class="history-wrap">
					<div class="history-list">
						<ul class="history-list-ul absol-0-0">
						<!-- 历史书籍输出 如果没有登录展示最近发布 start -->	
						<?php foreach ($this->sideBook as $sValue) { ?>
							<li>
								<a href="<?php echo $sValue['bookUrl']; ?>" title="点击查看详细信息">
									<img src="<?php echo $sValue['photo_path']; ?>">
								</a>
								<p>
									<a href="<?php echo $sValue['bookUrl']; ?>" title="点击查看详细信息"><?php echo $sValue['book_name']; ?></a>
								</p>
							</li>
						<?php } ?>
						<!-- 历史书籍输出 如果没有登录展示最近发布 end -->
						</ul>
					</div>

				</div>
			</div>
			<div class="clear"></div>
		</div>
		<script type="text/javascript">
			$(".spotlight-wrap").Slide({
				claNav: 'slide-nav',
				claCon: 'spotlight-list-ul',
   				effect : "scroolLoop",
   				speed : 'slow',
   				timer : 3000,
   				steps:1
			});
			// $('.get-tel').dialog(2);
		</script>
