<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
	<p>
		<div>这是头部</div><br>
		<div>
			content:<br>
			<?php echo $this->layout()->content ?>
		</div><br>
		<div>这是底部</div><br>
	</p>
</body>