<style type="text/css">
.zc_table{
	width:100%;
	color: #666;
}
.zc_table th{
	background: #F0F7FF;
	border: 1px solid #c9dae3;
	border-bottom: none;
	padding-top:2px;
	line-height:30px;
	font-size:13px;
}/*--20130711---Edit--*/
.zc_table td{
	background: #fff;
	border:1px solid #c9dae3;
	line-height:28px;
	padding:0 8px;
	font-size:13px;
}/*--20130711---Edit--*/
.tabs .text-section {
	background:#f9f9f9;
	padding:19px 0 8px 36px;
	margin:0 0 1px;
}
.nav-tabs{
	height: 24px;
	border-bottom: 1px solid #ddd;
	margin-bottom: 20px;
	margin-left: 0;
}
.nav-tabs>li{
	margin-bottom: -1px;
	float: left;
	line-height: 20px;
}
.nav-tabs>.active>a,.nav-tabs>.active>a:hover{
	color: #555;
	cursor: default;
	background: #fff;
	border: 1px solid #ddd;
	border-bottom-color: transparent;
}
.nav-tabs>li>a{
	padding: 8px 12px;
	margin-right: 2px;
	line-height: 20px;
	border-radius: 4px 4px 0 0 ;
}
.nav-tabs>li>a:hover{
	border-color: #eee #eee #ddd;
	text-decoration: none;
	background: #eee;
}
#content h2{
	color: #333;
	text-align: center;
	font-size: 16px;
}
/*#footer-wrap{
	position: absolute;
	bottom: 0px;
	left: 0px;
	width: 100%;
}*/
</style>
<!-- content -->
<div id="content" class="site-wrap">
	<h2>这是标题</h2>
	<div class="text-section">
		<ul class="nav-tabs">
			<li class="active">
				<a href="/admin/publish/type/1">交易中</a>
			</li>
			<li class="">
				<a href="/admin/publish/type/2">已完成的交易</a>
			</li>
			<li>
				<a href="/admin/userpublish/type/3">用户交易中</a>
			</li>
			<li>
				<a href="/admin/userpublish/type/4">用户完成交易</a>
			</li>
		</ul>
	</div>
	<table border="0" cellspacing="0" cellpadding="0" class="zc_table">
          <tr>
            <th>课题名称</th>
            <th >年级</th>
            <th >学科</th>
            <th >授课人</th>
            <th >听课人</th>
            <th >听课节数</th>
            <th >听课时间</th>
          </tr>
          <tr>
            <td align="center">古诗词三首</td>
            <td align="center">三年级</td>
            <td align="center">语文</td>
            <td align="center">尹江梅</td>
            <td align="center">杨素芳子</td>
            <td align="center">二节</td>
            <td align="center">2013-05-08</td>
          </tr>
        </table>
</div>

