<style type="text/css">
	article{
		font-size: 10px;
	}
	.pagination{
		float: right;
	}
</style>
<article>
	<div class="text-section">
		<h1>管理员信息信息</h1>
		<p>点击功能标签进行管理</p>
	</div>
	<div class="text-section">
		<ul class="nav nav-tabs">
			<li>
				<a href="/admin/user">易书友</a>
			</li>
			<li class="active">
				<a href="/admin/adminuser">管理员</a>
			</li>
		</ul>
	</div>
	<?php if ($this->userDegree == "super") { ?>
	<div class="text-section">
		<form class="form-inline" action="/admin/adminuser">
		    <label>
		        <input type="text" name="username" class="input-small" placeholder="name">
		    </label>
		    <input type="password" name="password" class="input-small" placeholder="Password">
		    <label class="radio">
			    <input type="radio" name="degree" value="normal" checked>normal
		    </label>
			  <input type="radio" name="degree" value="super">super
		    </label>
		    <button type="submit" class="btn">添加</button>
		</form>
	</div>
	<?php } ?>
	<table class="table table-hover table-striped table-bordered table-condensed">
		<thead>
			<th>管理员ID</th>
			<th>姓名</th>
			<?php  if ($this->userDegree == "super") { ?>
			<th>密码</th>
			<?php }?>
			<th>等级</th>
			<th>操作</th>
		</thead>
		<tbody>
			<!-- 书籍信息输出 start -->
			<?php for ($i=0; $i < count($this->admin); $i++) { ?>
			<tr>
				<td><?php echo $this->admin[$i]['admin_id']; ?></td>
				<td><?php echo $this->admin[$i]['name']; ?></td>
				<?php  if ($this->userDegree == "super") { ?>
				<td><?php echo $this->admin[$i]['pass']; ?></td>
				<?php }?>
				<td><?php echo $this->admin[$i]['degree']; ?></td>
				<td>
					<a href="" title="修改信息"><i class="icon-pencil"></i></a>&nbsp;&nbsp;&nbsp;
					<a href="" title="修改交易状态"><i class="icon-check"></i></a>
				</td>
			</tr>
			<?php } ?>
			<!-- 书籍信息输出 end -->
		</tbody>
	</table>
</article>