<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录</title>
<link rel="stylesheet" href="/css/reset.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/css/login.css" type="text/css" media="screen" />
<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body id="login">
  <div id="login-wrapper" class="png_bg">
    <div id="login-top">
      <a href="#"><img id="logo" src="/images/logo.png" alt="Simpla Admin logo" /></a> </div>
    <div id="login-content">
      <form class="form-horizontal" action="/admin/loginchk">
        <div class="control-group">
          <label class="control-label" for="inputEmail">Name</label>
          <div class="controls">
            <input type="text" name="username" id="inputEmail" placeholder="name">
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="inputPassword">Password</label>
          <div class="controls">
            <input type="password" name="password" id="inputPassword" placeholder="Password">
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Sign in</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>
</html>
