<style type="text/css">
	article{
		font-size: 10px;
	}
	.pagination{
		float: right;
	}
</style>
<article>
	<div class="text-section">
		<h1>全部发布的<b>求书</b>信息</h1>
		<p>点击功能标签进行管理</p>
	</div>
	<div class="text-section">
		<ul class="nav nav-tabs">
			<li class="<?php echo $this->seekingClass; ?>">
				<a href="/admin/seek/type/1">求书中</a>
			</li>
			<li class="<?php echo $this->seekedClass; ?>">
				<a href="/admin/seek/type/2">已关闭的求书</a>
			</li>
			<li>
				<a href="/admin/userseek/type/3">用户求书中</a>
			</li>
			<li>
				<a href="/admin/userseek/type/4">用户已关闭的交易</a>
			</li>
		</ul>
	</div>
	<table class="table table-hover table-striped table-bordered table-condensed">
		<thead>
			<th>交易ID</th>
			<th>书名</th>
			<th>信息</th>
			<th>求书时间</th>
			<th>求书状态</th>
			<th>用户名</th>
			<th>操作</th>
		</thead>
		<tbody>
			<!-- 书籍信息输出 start -->
			<?php for ($i=0; $i < count($this->buy['buy']); $i++) { ?>
			<tr>
				<td><?php echo $this->buy['buy'][$i]['buy_id']; ?></td>
				<td><?php echo $this->buy['buy'][$i]['buy_bookname']; ?></td>
				<td><?php echo $this->buy['buy'][$i]['buy_content']; ?></td>
				<td><?php echo $this->buy['buy'][$i]['time']; ?></td>
				<td><?php echo $this->buy['buy'][$i]['buy_state']; ?></td>
				<td><?php echo $this->buy['buy'][$i]['buy_username']; ?></td>
				<td>
					<?php if ($this->seekingClass) { ?>
					<a class="btn btn-small" href="javascript:void(0);" title="修改交易状态"><i class="icon-arrow-right seeking"></i>2</a>
					<?php } ?>
					<?php if ($this->seekedClass) { ?>
					<a class="btn btn-small" href="javascript:void(0);" title="修改交易状态">1<i class="icon-arrow-left seekhed"></i></a>&nbsp;&nbsp;
					<a class="btn btn-small" href="javascript:void(0);" title="修改交易状态"><i class="icon-trash seek"></i>Del</a>
					<?php } ?>
				</td>
			</tr>
			<?php } ?>
			<!-- 书籍信息输出 end -->
		</tbody>
	</table>
	<div class="row">
		<div class="span4"></div>
	    <div class="span5">
	    	<div class="pagination">
				<ul>
					<li><a style="<?php echo $this->pageNav['firstStyle']; ?>" href="<?php echo $this->pageNav['firstUrl']; ?>">首页</a></li>
					<li><a style="<?php echo $this->pageNav['preStyle']; ?>" href="<?php echo $this->pageNav['preUrl']; ?>"><i class="icon-arrow-left"></i></a></li>
					<li><a href="javascript:void(0)"><?php echo $this->page; ?>/<?php echo $this->pages; ?></a></li>
					<li><a style="<?php echo $this->pageNav['nextStyle']; ?>" href="<?php echo $this->pageNav['nextUrl']; ?>"><i class="icon-arrow-right"></i></a></li>
					<li><a style="<?php echo $this->pageNav['lastStyle']; ?>" href="<?php echo $this->pageNav['lastUrl']; ?>">尾页</a></li>
				</ul>
			</div>
		</div>
	</div>
</article>