<style type="text/css">
	article{
		font-size: 10px;
	}
	.pagination{
		float: right;
	}
</style>
<article>
	<div class="text-section">
		<h1>查询用户求书信息</h1>
		<p>点击功能标签进行管理</p>
	</div>
	<div class="text-section">
		<ul class="nav nav-tabs">
			<li>
				<a href="/admin/seek/type/1">求书中</a>
			</li>
			<li>
				<a href="/admin/seek/type/2">已关闭的求书</a>
			</li>
			<li class="<?php echo $this->useekingClass; ?>">
				<a href="/admin/userseek/type/3">用户求书中</a>
			</li>
			<li class="<?php echo $this->useekedClass; ?>">
				<a href="/admin/userseek/type/4">用户已关闭的交易</a>
			</li>
		</ul>
	</div>
	<div class="text-section">
		<form class="form-search" action="/admin/userseek">
			<label for="user-id">用户名：</label>
		    <select name="user-id" id="">
		    	<option value=""></option>
		    	<!-- 用户信息输出 -->
		    	<?php foreach ($this->userInfo as $userValue) { ?>
		    	<option value="<?php echo $userValue['user_id']; ?>"><?php echo $userValue['user_name']; ?></option>
		    	<?php } ?>
		    </select> 
		    <i class="icon-tasks"></i>
		    <div class="input-prepend">
                <span class="add-on">@</span>
                <input name="user-name" class="span2" id="prependedInput" type="text" placeholder="Username">
            </div>
            <input type="hidden" name="type" value="<?php echo $this->searchType; ?>">
		    <button type="submit" class="btn">Search</button>
		</form>
	</div>
	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<th>交易ID</th>
			<th>书名</th>
			<th>信息</th>
			<th>求书时间</th>
			<th>求书状态</th>
			<th>用户名</th>
			<th>操作</th>
		</thead>
		<tbody>
			<!-- 书籍信息输出 start -->
			<?php for ($i=0; $i < count($this->buy); $i++) { ?>
			<tr>
				<td><?php echo $this->buy[$i]['buy_id']; ?></td>
				<td><?php echo $this->buy[$i]['buy_bookname']; ?></td>
				<td><?php echo $this->buy[$i]['buy_content']; ?></td>
				<td><?php echo $this->buy[$i]['time']; ?></td>
				<td><?php echo $this->buy[$i]['buy_state']; ?></td>
				<td><?php echo $this->buy[$i]['buy_username']; ?></td>
				<td>
					<?php if ($this->useekingClass) { ?>
					<a class="btn btn-small" href="javascript:void(0);" title="修改交易状态"><i class="icon-arrow-right seeking"></i>2</a>
					<?php } ?>
					<?php if ($this->useekedClass) { ?>
					<a class="btn btn-small" href="javascript:void(0);" title="修改交易状态">1<i class="icon-arrow-left seekhed"></i></a>&nbsp;&nbsp;
					<a class="btn btn-small" href="javascript:void(0);" title="修改交易状态"><i class="icon-trash seek"></i>Del</a>
					<?php } ?>
				</td>
			</tr>
			<?php } ?>
			<!-- 书籍信息输出 end -->
		</tbody>
	</table>
	<div class="row">
		<div class="span4"></div>
	    <div class="span5">
	    	<div class="pagination">
				<ul>
					<li><a style="<?php echo $this->pageNav['firstStyle']; ?>" href="<?php echo $this->pageNav['firstUrl']; ?>">首页</a></li>
					<li><a style="<?php echo $this->pageNav['preStyle']; ?>" href="<?php echo $this->pageNav['preUrl']; ?>"><i class="icon-arrow-left"></i></a></li>
					<li><a href="javascript:void(0)"><?php echo $this->page; ?>/<?php echo $this->pages; ?></a></li>
					<li><a style="<?php echo $this->pageNav['nextStyle']; ?>" href="<?php echo $this->pageNav['nextUrl']; ?>"><i class="icon-arrow-right"></i></a></li>
					<li><a style="<?php echo $this->pageNav['lastStyle']; ?>" href="<?php echo $this->pageNav['lastUrl']; ?>">尾页</a></li>
				</ul>
			</div>
		</div>
	</div>
</article>